<a href="https://colab.research.google.com/github/sgcortes/2023_NAPLES/blob/main/Lect1_0b_Python_NumPy_Reminder_short.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<table style="width:100%">
  <tr>
    <td><img src="https://unioviedo-my.sharepoint.com/:i:/g/personal/sgcortes_uniovi_es/Ebr0ybKDTBNKtoJyzmTBuRYBXY7nE-cCYaH-WDIVJxEVWA?&download=1" width="211" height="69" alt="Uniovi & EP Mieres logos" title="Uniovi & EP Mieres logos" /></td>
    <td><font color=brown>ML&DL Naples 2023<br></font>
    <font color=green>Universidad de Oviedo. <br>Ingeniería en Geomática</font> <br><br>sgcortes@uniovi.es</td>
  </tr>
</table>

## T1. Repaso: NumPy

NumPy es un pquete para el cálculo cientifico con Python que integra un objeto matricial N-dimensional, algebra lineal, trasnformada de Fourier y capacidades de generación de números aleatorios. La mayoría de los paquetes que trabajan con imágenes generan o puede convertirse su salida, a una matriz de NumPy por ello es necesario manejar algunas de sus funciones relacionadas con la manipulación de matrices.( http://www.numpy.org/ ).
El paquete NumPy debe importarse como sigue:

In [ ]:
import numpy as np

## Funciones para crear matrices

Algunas funciones básicas para crear matrices son las siguientes:

In [ ]:
matriz_1= np.array([[1,2,3,4],[5,6,7,8]])
print(matriz_1)

[[1 2 3 4]
 [5 6 7 8]]


Observese que se ha construido una matriz 2x4, empleando como elementos dos "listas" que corresponden a las dos filas separadas por comas. Adicionalmente las dos filas se encierran a su vez por un nuevo par de corchetes. 

El indexado en las matrices, para hacer referencia a un elemento, se realiza con corchetes también de este modo:

In [ ]:
print(matriz_1[0,3])

4


Otras funciones para crear ciertas matrices pueden ser:
- np.ones(): Crea matrices con unos 
- np.zeros(): Crea matrices de ceros
- np.random(): Matrices de números aleatorios
- np.full(): Matriz completa (densa) con elementos que son constantes

In [ ]:
unos=np.ones((3,2)) # recibe una tupla como argumento por esos va entre paréntensis
print(unos)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
ceros=np.zeros((2,3))
print(ceros)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
alea=np.random.random(3) # Matrices de valores aleatorios
print(alea)

[0.63097045 0.64789072 0.88756414]


In [ ]:
llena=np.full((2,2), 6)
print(llena)

[[6 6]
 [6 6]]


In [ ]:
vacia=np.empty((3,4))
print(vacia)

[[7.18942804e-312 3.16202013e-322 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 3.88452374e-057 6.15534277e+170 1.34940190e+161]
 [3.59967195e+179 1.48643067e-076 5.79682563e+170 4.69625634e-033]]


In [ ]:
I=np.eye(2) # necesita un entero
print(I)
I2=np.identity(4) # necesita un entero
print(I2)

[[1. 0.]
 [0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Dos funciones importantes son la función **copy** y la opción de especificar el tipo de datos que se desea tenga los elementos de la matriz creada.

In [ ]:
d=np.full((2,2), 7,dtype=np.float32)
print(d)

[[7. 7.]
 [7. 7.]]


In [ ]:
a=I.copy()
print('Matriz a:\n',a)
print('Matriz I:\n', I)

Matriz a:
 [[1. 0.]
 [0. 1.]]
Matriz I:
 [[1. 0.]
 [0. 1.]]


Las funciónes (métodos) **arange()** y **linspace()** puede emplearse para crear vectores (matrices de 1 dimensión) 

In [ ]:
a=np.arange(0,10,2)
print(a)

[0 2 4 6 8]


In [ ]:
b=np.arange(6)
print(b)

[0 1 2 3 4 5]


In [ ]:
c=np.linspace(0,10,6) # con linspace se limitan el número de elementos
print(c)

[ 0.  2.  4.  6.  8. 10.]


### Propiedades básicas de las matrices

Las características básicas de las matrices peuden accederse mediante las propiedades de los objetos de la clase **Numpy**

In [ ]:
print('Número de dimensiones:',matriz_1.ndim)
print('Dimensiones:', matriz_1.shape)
print('Número de elementos:', matriz_1.size)
print('Tipo de datos del objeto:' ,type(matriz_1))

Número de dimensiones: 2
Dimensiones: (2, 4)
Número de elementos: 8
Tipo de datos del objeto: <class 'numpy.ndarray'>


### Cambiando forma y tamaño

Los métodos siguientes permiten cambiar la forma y el tamaño de la matriz: 

In [ ]:
m=np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9,10,11,12]])
print(m)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
m.resize(2,6)
print(m)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [ ]:
print(m.ravel())

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
print(m)


[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [ ]:
p=m.ravel()
print(p)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
q=p.reshape(6,2)
print(q)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [ ]:
print(q.transpose())

[[ 1  3  5  7  9 11]
 [ 2  4  6  8 10 12]]


### Slicing: Extrayendo submatrices 

Los rangos de índices para  las submatrices a extraer se definen con tres valores: start, stop, step, los dos valores primeros son índices y el tercero indica el número de elementos a extraer.

In [ ]:
q=q.ravel()
print(q)
print('Extrayendo ')
print(q[3:9:2]) # el elemento de índice 9 no se extrae, pero sí el de índice 3

[ 1  2  3  4  5  6  7  8  9 10 11 12]
Extrayendo 
[4 6 8]


Si la matriz es multidimensional se especifica el rango deseado en todas las dimensiones (e.g filas y cols, [0:7:2, 1] para extraer elementos de la col=1)

In [ ]:
q=q.reshape(3,4)
print(q)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
r=q[1:3, 1:3] # los elementos de índice 3 no se extraen
print(r)

[[ 6  7]
 [10 11]]


Para extraer toda una fila o toda una columna simplemente se omite el valor del final del rango despues de los dos puntos (:):

In [ ]:
t=q[:,2]
print('La tercera columna de q vale:', t)

La tercera columna de q vale: [ 3  7 11]


In [ ]:
print(q)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
z=q[2:,:]
print(z)

[[ 9 10 11 12]]


También los puntos supensivos **"..."** pueden emplearse para indicar todos los elementos en una dirección.

In [ ]:
print(q[...,3])

[ 4  8 12]


In [ ]:
print(q[:,3])

[ 4  8 12]


### Operaciones aritméticas
Arithmetic operations are made element by element.

In [ ]:
x=np.array([[1,2,3],[4,5,6]])
y=np.array([[7,8,9],[10,11,12]])
print(x+y)

[[ 8 10 12]
 [14 16 18]]


In [ ]:
print(np.remainder(y,x))

[[0 0 0]
 [2 1 0]]


In [ ]:
print(x**2)

[[ 1  4  9]
 [16 25 36]]


In [ ]:
print(y-x)

[[6 6 6]
 [6 6 6]]


### Otras funciones

In [ ]:
print(x<5)

[[ True  True  True]
 [ True False False]]


Estas funciones trabajan elemento a elemento:
- np.around() :Redondea al entero mas cercano
- np.trunc() : trunca los decimales de lso elementos
- np.floor() : redondea al entero menor
- np.ceil() : redondea al entero mayor
- np.log() : logaritmo

In [ ]:
print(x)
print(np.min(x)) # mínimo de toda la matriz
print(np.max(x, axis=0)) # calcula màximos por cada columna
print(np.cumsum(x)) # suma acumulativa de los elementos
print(x.std()) # desviación estandar

[[1 2 3]
 [4 5 6]]
1
[4 5 6]
[ 1  3  6 10 15 21]
1.707825127659933
