<a href="https://colab.research.google.com/github/sgcortes/2023_NAPLES/blob/main/nLect1_0b_Python_NumPy_Reminder_short.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<table style="width:100%">
  <tr>
    <td><img src="https://unioviedo-my.sharepoint.com/:i:/g/personal/sgcortes_uniovi_es/Ebr0ybKDTBNKtoJyzmTBuRYBXY7nE-cCYaH-WDIVJxEVWA?&download=1" width="211" height="69" alt="Uniovi & EP Mieres logos" title="Uniovi & EP Mieres logos" /></td>
    <td><font color=brown>ML&DL Naples 2023<br></font>
    <font color=green>Universidad de Oviedo. <br>Ingeniería en Geomática</font> <br><br>sgcortes@uniovi.es</td>
  </tr>
</table>

##  NumPy

NumPy is a Python scientific computing package that integrates N-dimensional matrix object, linear algebra, Fourier transform and random number generation capabilities. Most packages that work with images generate, or can convert their output into a NumPy matrix, so it is necessary to handle some of its matrix manipulation functions (http://www.numpy.org/ ). The NumPy package must be imported as follows:

In [192]:
import numpy as np

## Matrix (or array) creation function:

Some basic functions for creating matrices are as follows:

In [193]:
matriz_1= np.array([[1,2,3,4],[5,6,7,8]])
print(matriz_1)

[[1 2 3 4]
 [5 6 7 8]]


Note that a 2x4 matrix has been constructed, using as elements two "lists" corresponding to the two rows separated by commas. Additionally, the two rows are enclosed by a new pair of square brackets. 

The indexing in the matrices, to refer to an element, is also done with square brackets in this way:


In [194]:
print(matriz_1[0,3])

4


Other functions to create certain arrays may include:
- np.ones(): Creates arrays with ones 
- np.zeros(): Creates arrays of zeros
- np.random(): arrays of random numbers
- np.full(): full (dense) array with elements that are constants


In [195]:
unos=np.ones((3,2)) # recibe una tupla como argumento por esos va entre paréntensis
print(unos)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [196]:
ceros=np.zeros((2,3))
print(ceros)

[[0. 0. 0.]
 [0. 0. 0.]]


In [197]:
alea=np.random.random(3) # Matrices de valores aleatorios
print(alea)

[0.22029166 0.57624257 0.3167498 ]


In [198]:
llena=np.full((2,2), 6)
print(llena)

[[6 6]
 [6 6]]


In [199]:
vacia=np.empty((3,4))
print(vacia)

[[4.9e-324 9.9e-324 1.5e-323 2.0e-323]
 [2.5e-323 3.0e-323 3.5e-323 4.0e-323]
 [4.4e-323 4.9e-323 5.4e-323 5.9e-323]]


In [200]:
I=np.eye(2) # necesita un entero
print(I)
I2=np.identity(4) # necesita un entero
print(I2)

[[1. 0.]
 [0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Two important functions are the **copy** function and the option to specify the type of data you want the elements of the created array to have.

In [201]:
d=np.full((2,2), 7,dtype=np.float32)
print(d)

[[7. 7.]
 [7. 7.]]


In [202]:
a=I.copy()
print('Matriz a:\n',a)
print('Matriz I:\n', I)

Matriz a:
 [[1. 0.]
 [0. 1.]]
Matriz I:
 [[1. 0.]
 [0. 1.]]


The **arange()** and **linspace()** functions (methods) can be used to create vectors (1-dimensional arrays).

In [203]:
a=np.arange(0,10,2) # (start,stop,step)

In [204]:
b=np.arange(6)
print(b)

[0 1 2 3 4 5]


In [205]:
c=np.linspace(0,10,6) # 6 in this case is the unmber of desired elements
print(c)

[ 0.  2.  4.  6.  8. 10.]


### Basic matrix properties

The basic characteristics of arrays can be accessed through the properties of objects of the **Numpy** class.

In [206]:
print('Número de dimensiones:',matriz_1.ndim)
print('Dimensiones:', matriz_1.shape)
print('Número de elementos:', matriz_1.size)
print('Tipo de datos del objeto:' ,type(matriz_1))

Número de dimensiones: 2
Dimensiones: (2, 4)
Número de elementos: 8
Tipo de datos del objeto: <class 'numpy.ndarray'>


### Changing shape and size

The following methods allow you to change the shape and size of the matrix:

In [207]:
m=np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9,10,11,12]])
print(m)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [208]:
m.resize(2,6)
print(m)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [209]:
print(m.ravel())
print(m.shape)
b= m.ravel()
print(b.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
(2, 6)
(12,)


In [210]:
print(m)
vec = m.flatten()
print(vec)
print(vec.shape)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)


In [211]:
p=m.ravel()
print(p)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [212]:
q=p.reshape(6,2)
print(q)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [213]:
print(q.transpose())

[[ 1  3  5  7  9 11]
 [ 2  4  6  8 10 12]]


### Slicing: sub-matrices 

The index ranges for the sub-matrices to be extracted are defined with three values: start, stop, step, the first two values are indices and the third one indicates the number of elements to be extracted.

In [214]:
q=q.ravel()
print(q)
print('Extrayendo ')
print(q[3:9:2]) # el elemento de índice 9 no se extrae, pero sí el de índice 3

[ 1  2  3  4  5  6  7  8  9 10 11 12]
Extrayendo 
[4 6 8]


If the matrix is multidimensional, specify the desired range in all dimensions (e.g. rows and cols, [0:7:2, 1] to extract elements from col=1).

In [215]:
q=q.reshape(3,4)
print(q)

print(q[0:3:1, 1])
x = q[0:3:1, 1]
print(x.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 2  6 10]
(3,)


In [216]:
r=q[1:3, 1:3] # los elementos de índice 3 no se extraen
print(r)

[[ 6  7]
 [10 11]]


To extract an entire row or column, simply omit the value at the end of the range after the colon (:):

In [217]:
t=q[:,2]
print('La tercera columna de q vale:', t)

La tercera columna de q vale: [ 3  7 11]


In [218]:
print(q)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [219]:
z=q[2:,:]
print(z)

[[ 9 10 11 12]]


Also the supensive dots **"... "** can be used to indicate all elements in one direction.

In [220]:
print(q[...,3])

[ 4  8 12]


In [221]:
print(q[:,3])

[ 4  8 12]


### Arithmetic operations
Arithmetic operations are made element by element.

In [222]:
x=np.array([[1,2,3],[4,5,6]])
y=np.array([[7,8,9],[10,11,12]])
print(x+y)

[[ 8 10 12]
 [14 16 18]]


In [228]:
print(np.remainder(y,x))

[[0 0 0]
 [2 1 0]]


In [229]:
print(x**2)

[[ 1  4  9]
 [16 25 36]]


In [230]:
print(y-x)

[[6 6 6]
 [6 6 6]]


### Other functions

In [226]:
print(x<5)

[[ True  True  True]
 [ True False False]]


Estas funciones trabajan elemento a elemento:
- np.around() :Redondea al entero mas cercano
- np.trunc() : trunca los decimales de lso elementos
- np.floor() : redondea al entero menor
- np.ceil() : redondea al entero mayor
- np.log() : logaritmo

In [227]:
print(x)
print(np.min(x)) # mínimo de toda la matriz
print(np.max(x, axis=0)) # calcula màximos por cada columna
print(np.cumsum(x)) # suma acumulativa de los elementos
print(x.std()) # desviación estandar

[[1 2 3]
 [4 5 6]]
1
[4 5 6]
[ 1  3  6 10 15 21]
1.707825127659933
